INSERT INTO question VALUES
(1, 'Java', 'E', 'Question - Easy 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(2, 'Python', 'E', 'Question - Easy 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(3, 'Rust', 'E', 'Question - Easy 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(4, 'C', 'E', 'Question - Easy 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(5, 'Java', 'E', 'Question - Easy 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(6, 'Javascript', 'M', 'Question - Medium 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(7, 'C++', 'M', 'Question - Medium 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(8, 'Java', 'M', 'Question - Medium 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(9, 'Rust', 'M', 'Question - Medium 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(10, 'Java', 'M', 'Question - Medium 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(11, 'Spring', 'H', 'Question - Hard 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(12, 'Java EE', 'H', 'Question - Hard 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(13, 'Docker', 'H', 'Question - Hard 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(14, 'AWS', 'H', 'Question - Hard 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(15, 'Cloud', 'H', 'Question - Hard 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(16, 'Java', 'E', 'Question - Easy 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(17, 'Python', 'E', 'Question - Easy 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(18, 'Rust', 'E', 'Question - Easy 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(19, 'C', 'E', 'Question - Easy 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(20, 'Java', 'E', 'Question - Easy 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(21, 'Javascript', 'M', 'Question - Medium 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(22, 'C++', 'M', 'Question - Medium 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(23, 'Java', 'M', 'Question - Medium 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(24, 'Rust', 'M', 'Question - Medium 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(25, 'Java', 'M', 'Question - Medium 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(26, 'Spring', 'H', 'Question - Hard 01', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)'),
(27, 'Java EE', 'H', 'Question - Hard 02', 'option a)', 'option b)', 'option c)', 'option d)', 'option c)'),
(28, 'Docker', 'H', 'Question - Hard 03', 'option a)', 'option b)', 'option c)', 'option d)', 'option b)'),
(29, 'AWS', 'H', 'Question - Hard 04', 'option a)', 'option b)', 'option c)', 'option d)', 'option a)'),
(30, 'Cloud', 'H', 'Question - Hard 05', 'option a)', 'option b)', 'option c)', 'option d)', 'option d)');